import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import { join, resolve } from "node:path";
import type { LoadedTheme, ThemeManifest } from "./manifest.js";
import type { DesignTokens } from "../templates/types.js";
import { loadThemeTemplates } from "./templateLoader.js";

/**
 * Default search roots for disk themes. The order matters — later roots
 * win on id collision so a project can override a repo-shipped theme.
 *
 *   1. <repo>/docs/design-systems/    — themes shared across projects,
 *      committed to the repo.
 *   2. <project>/themes/              — project-local themes, dropped by
 *      a designer or generated by Claude design.
 *
 * The repo root is found by walking up from this module's path until we
 * hit a directory containing `package.json` with name "@hyperframes/core"
 * or a `pnpm-workspace.yaml` / `bun.lockb` / `bun.lock` — anything that
 * looks like the workspace root.
 */
export interface ThemeSearchRoots {
  repoRoot?: string;
  projectDir?: string;
}

export function discoverThemeRoots(opts: ThemeSearchRoots): string[] {
  const roots: string[] = [];
  if (opts.repoRoot) {
    const repoThemes = join(opts.repoRoot, "docs", "design-systems");
    if (existsSync(repoThemes)) roots.push(repoThemes);
  }
  if (opts.projectDir) {
    const projectThemes = join(opts.projectDir, "themes");
    if (existsSync(projectThemes)) roots.push(projectThemes);
  }
  return roots;
}

/**
 * Walk one search root and load every valid theme manifest under it.
 * A "theme folder" is any direct child directory that contains a
 * theme.json. Anything else is silently skipped — that lets the same
 * folder hold reference docs, JSX sources, etc. without polluting the
 * registry.
 */
export function loadThemesFromRoot(rootDir: string): LoadedTheme[] {
  if (!existsSync(rootDir)) return [];
  const out: LoadedTheme[] = [];
  let entries: string[];
  try {
    entries = readdirSync(rootDir);
  } catch {
    return [];
  }
  for (const name of entries) {
    const folder = join(rootDir, name);
    let isDir = false;
    try {
      isDir = statSync(folder).isDirectory();
    } catch {
      continue;
    }
    if (!isDir) continue;
    const manifestPath = join(folder, "theme.json");
    if (!existsSync(manifestPath)) continue;
    let raw: unknown;
    try {
      raw = JSON.parse(readFileSync(manifestPath, "utf-8"));
    } catch {
      continue;
    }
    const loaded = materializeTheme(raw, folder);
    if (loaded) out.push(loaded);
  }
  return out;
}

/**
 * Convert a parsed manifest plus its folder location into a runtime
 * LoadedTheme: validates required fields, resolves filesystem paths,
 * inlines the designSystemDoc so callers get all the data in one shot.
 * Returns null when the manifest is malformed.
 */
export function materializeTheme(raw: unknown, folder: string): LoadedTheme | null {
  if (!raw || typeof raw !== "object") return null;
  const m = raw as Partial<ThemeManifest>;
  if (typeof m.id !== "string" || !m.id.trim()) return null;
  if (!m.tokens || !validateTokens(m.tokens)) return null;
  const designSystemDoc = m.designSystemDoc ? safeReadText(join(folder, m.designSystemDoc)) : null;
  const referenceRenderPath = m.referenceRender
    ? safeAbsolutePath(join(folder, m.referenceRender))
    : null;
  return {
    id: m.id,
    name: typeof m.name === "string" ? m.name : m.id,
    description: typeof m.description === "string" ? m.description : "",
    tokens: m.tokens,
    fonts: { googleFonts: m.fonts?.googleFonts ?? [] },
    preferences: {
      atmospheres: m.preferences?.atmospheres ?? [],
      transitions: m.preferences?.transitions ?? [],
      icons: m.preferences?.icons ?? [],
    },
    designSystemDoc,
    referenceRenderPath,
    templates: loadThemeTemplates(folder, m.id),
    source: `disk:${folder}`,
  };
}

function safeReadText(path: string): string | null {
  try {
    if (!existsSync(path)) return null;
    return readFileSync(path, "utf-8");
  } catch {
    return null;
  }
}

function safeAbsolutePath(path: string): string | null {
  try {
    if (!existsSync(path)) return null;
    return resolve(path);
  } catch {
    return null;
  }
}

function validateTokens(t: unknown): t is DesignTokens {
  if (!t || typeof t !== "object") return false;
  const tt = t as Partial<DesignTokens>;
  if (!tt.colors || typeof tt.colors !== "object") return false;
  if (!tt.fonts || typeof tt.fonts !== "object") return false;
  if (!tt.motion || typeof tt.motion !== "object") return false;
  // Must have at minimum bg + fg + accent colors and the three font slots.
  const c = tt.colors as Record<string, unknown>;
  const f = tt.fonts as Record<string, unknown>;
  return (
    typeof c.bg === "string" &&
    typeof c.fg === "string" &&
    typeof c.accent === "string" &&
    typeof f.display === "string" &&
    typeof f.body === "string" &&
    typeof f.mono === "string"
  );
}
